line:
  bot:
    channel-token: W69a21ar+l5KJeHgsCISqBJSUiEQMfc3zUFpydqZUTMlzqceKNhrswSBniMswD6ZVpG8nMfArPeLTpzK/hqzI+2cK/xr2L7z8oYAU/vKoMrz4DX7JZFEjbJrStYF4S1W8Lr9kw9vDr6PR8u8YkHcdwdB04t89/1O/w1cDnyilFU=
    channel-secret: 3046fe222fb8ad26c422375555a1230d
    handler.path: /callback

logging:
  file: logs/myapp.log
  level:
    org.springframework.web: INFO